server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  client:
    # Eureka Server не будет пытаться зарегистрироваться сам в себе.
    register-with-eureka: false
    # Eureka Server не будет пытаться получить реестр от других Eureka Server.
    fetch-registry: false
