spring:
  main:
    banner-mode: off
    log-startup-info: false
  jackson:
    serialization.INDENT_OUTPUT: true

logging:
  level:
    ru.yandex.practicum.telemetry: info
    org:
      springframework: error
      apache.kafka: warn
